//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppOGL.Entities.Administracion
{
    using System;
    using System.Collections.Generic;
    
    public partial class adm_empleados
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public string Nombres { get; set; }
        public string Apellido_Paterno { get; set; }
        public string Apellido_Materno { get; set; }
        public Nullable<int> adm_puestos_Id { get; set; }
        public string Email { get; set; }
        public Nullable<int> adm_area_Id { get; set; }
    
        public virtual adm_area adm_area { get; set; }
        public virtual adm_puestos adm_puestos { get; set; }
    }
}
