//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppOGL.Entities.OrdenesCompra
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_a3f19c_administracionEntities2 : DbContext
    {
        public db_a3f19c_administracionEntities2()
            : base("name=db_a3f19c_administracionEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<oc_categoria> oc_categoria { get; set; }
        public virtual DbSet<oc_centrocostos> oc_centrocostos { get; set; }
        public virtual DbSet<oc_det_ordenes_productos> oc_det_ordenes_productos { get; set; }
        public virtual DbSet<oc_divisa> oc_divisa { get; set; }
        public virtual DbSet<oc_formapago> oc_formapago { get; set; }
        public virtual DbSet<oc_lugarentrega> oc_lugarentrega { get; set; }
        public virtual DbSet<oc_proveedores> oc_proveedores { get; set; }
        public virtual DbSet<oc_subcentrocostos> oc_subcentrocostos { get; set; }
        public virtual DbSet<oc_tipocompra> oc_tipocompra { get; set; }
        public virtual DbSet<UoM> UoM { get; set; }
        public virtual DbSet<oc_solicitantes> oc_solicitantes { get; set; }
        public virtual DbSet<oc_supervisores> oc_supervisores { get; set; }
        public virtual DbSet<oc_statuscompras> oc_statuscompras { get; set; }
        public virtual DbSet<oc_statusdirector> oc_statusdirector { get; set; }
        public virtual DbSet<oc_statusfinanzas> oc_statusfinanzas { get; set; }
        public virtual DbSet<oc_statussupervisor> oc_statussupervisor { get; set; }
        public virtual DbSet<oc_productos> oc_productos { get; set; }
        public virtual DbSet<oc_ordenescompras> oc_ordenescompras { get; set; }
    }
}
