//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppOGL.Entities.OrdenesCompra
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_det_ordenes_productos
    {
        public int Id { get; set; }
        public string Codigo { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<decimal> Subtotal { get; set; }
        public int oc_ordenescompras_Id { get; set; }
        public int oc_productos_Id { get; set; }
    
        public virtual oc_ordenescompras oc_ordenescompras { get; set; }
        public virtual oc_productos oc_productos { get; set; }
    }
}
