//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppOGL.Entities.OrdenesCompra
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_detproveedorcategoria
    {
        public int Id { get; set; }
        public int oc_proveedores_Id { get; set; }
        public int oc_categoriaproveedores_Id { get; set; }
    
        public virtual oc_categoriaproveedores oc_categoriaproveedores { get; set; }
        public virtual oc_proveedores oc_proveedores { get; set; }
    }
}
