//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppOGL.Entities.OrdenesCompra
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_productos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public oc_productos()
        {
            this.oc_det_ordenes_productos = new HashSet<oc_det_ordenes_productos>();
        }
    
        public int Id { get; set; }
        public string Descripcion { get; set; }
        public int UoM_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<oc_det_ordenes_productos> oc_det_ordenes_productos { get; set; }
        public virtual UoM UoM { get; set; }
    }
}
