//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppOGL.Entities.OrdenesCompra
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_supervisores
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public oc_supervisores()
        {
            this.oc_solicitantes = new HashSet<oc_solicitantes>();
        }
    
        public int Id { get; set; }
        public string NombreCompleto { get; set; }
        public int adm_empleados_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<oc_solicitantes> oc_solicitantes { get; set; }
    }
}
