//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppOGL.Entities.Bitacora
{
    using System;
    using System.Collections.Generic;
    
    public partial class sis_bitacoras_error
    {
        public int Id { get; set; }
        public string Controlador { get; set; }
        public string Vista { get; set; }
        public string Mensaje { get; set; }
        public Nullable<System.DateTime> FechaError { get; set; }
    }
}
