//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppOGL.Entities.OrdenesServicio
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_a3f19c_administracionEntities3 : DbContext
    {
        public db_a3f19c_administracionEntities3()
            : base("name=db_a3f19c_administracionEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<os_detos_conceptos> os_detos_conceptos { get; set; }
        public virtual DbSet<os_detrutas_destinos> os_detrutas_destinos { get; set; }
        public virtual DbSet<os_origen> os_origen { get; set; }
        public virtual DbSet<os_rutas> os_rutas { get; set; }
        public virtual DbSet<os_statuscompras> os_statuscompras { get; set; }
        public virtual DbSet<os_conceptos> os_conceptos { get; set; }
        public virtual DbSet<os_destinos> os_destinos { get; set; }
        public virtual DbSet<os_ordenesservicio> os_ordenesservicio { get; set; }
    }
}
