//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppOGL.Entities.OrdenesServicio
{
    using System;
    using System.Collections.Generic;
    
    public partial class os_facturas_compras
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> FechaRecibido { get; set; }
        public string NumeroFactura { get; set; }
        public int os_ordenesservicio_Id { get; set; }
    
        public virtual os_ordenesservicio os_ordenesservicio { get; set; }
    }
}
