//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppOGL.Entities.Sistemas
{
    using System;
    using System.Collections.Generic;
    
    public partial class sis_asignacion_impresoras
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> FechaAsignacion { get; set; }
        public int sis_impresoras_Id { get; set; }
        public int adm_area_Id { get; set; }
        public int adm_sucursales_Id { get; set; }
        public int sis_mantenimiento_Id { get; set; }
        public int adm_cuentas_Id { get; set; }
    
        public virtual sis_impresoras sis_impresoras { get; set; }
        public virtual sis_mantenimiento sis_mantenimiento { get; set; }
    }
}
