//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppOGL.Entities.Sistemas
{
    using System;
    using System.Collections.Generic;
    
    public partial class sis_celulares
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public string Modelo { get; set; }
        public string Numero_Producto { get; set; }
        public string IMEI { get; set; }
        public string Color { get; set; }
        public string Cargador { get; set; }
        public string OS { get; set; }
        public string Almacenamiento { get; set; }
        public string RAM { get; set; }
        public string Procesador { get; set; }
        public string Pantalla { get; set; }
        public string Camara_Frontal { get; set; }
        public string Camara_Trasera { get; set; }
        public int sis_mantenimiento_Id { get; set; }
        public int sis_estatusequipo_Id { get; set; }
        public int sis_marcas_Id { get; set; }
    
        public virtual sis_estatusequipo sis_estatusequipo { get; set; }
        public virtual sis_mantenimiento sis_mantenimiento { get; set; }
        public virtual sis_marcas sis_marcas { get; set; }
    }
}
